---
name: Trivy Java DB

on:
  workflow_dispatch:

env:
  DB_VERSION: 1
  GH_OWNER: steviegs
  IMAGE_NAME: java-vuln-db-localbuild
  REGISTRY: ghcr.io

permissions:
  packages: write # for GHCR
  contents: read

jobs:
  build:
    name: Build DB
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
        id: go

      - name: Install ORAS
        run: |
          curl -LO https://github.com/oras-project/oras/releases/download/v1.2.0/oras_1.2.0_linux_amd64.tar.gz
          tar -xvf oras_1.2.0_linux_amd64.tar.gz
          sudo mv oras /usr/local/bin/
          oras version

      - name: Pull existing trivy-java-db
        run: |
          mkdir -p ./cache/db
          if oras pull "ghcr.io/aquasecurity/trivy-java-db:1"; then
            tar -xvf javadb.tar.gz -C ./cache/db
            echo "Previous DB pulled successfully."
          else
            echo "No existing DB found. Continuing..."
          fi

      - name: Build binary
        run: make build

      - name: Crawl indexes
        run: make db-crawl

      - name: Build database
        run: make db-build

      - name: Compress database
        run: make db-compress

      - name: Prepare DB artifact
        run: mv cache/db/javadb.tar.gz .


      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push DB to GHCR
        run: |
          FULL_IMAGE="${{ env.REGISTRY }}/${{ env.GH_OWNER }}/${{ env.IMAGE_NAME }}:${{ env.DB_VERSION }}"
          
          echo "Pushing ${FULL_IMAGE}"
          
          oras push \
            --artifact-type application/vnd.aquasec.trivy.config.v1+json \
            "${FULL_IMAGE}" \
            javadb.tar.gz:application/vnd.aquasec.trivy.javadb.layer.v1.tar+gzip
          
          echo "Push completed successfully."

